# SDR++ settings, may also work with other Hamlib/Rigctl compatible SDR software
# IP address of SDR
SDR_IP: 127.0.0.1
# Port number of SDR
SDR_PORT: 4532

# RUMlogNG settings, may also work with other DX-lab suite Commander compatible logging software
Logger_IP: 127.0.0.1
Logger_PORT: 5555

# Will automatically reconnect to logging software or SDR every "Reconnect_time" seconds
Reconnect_time: 10  # seconds
# Will sync SDR with logging software every "Sync_time" seconds
Sync_time: 0.05  # seconds